name: Write media.json test (explicit push)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main (not detached)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Show repo state before changes
        run: |
          set -x
          git rev-parse --abbrev-ref HEAD
          git status
          git remote -v
          ls -la

      - name: Create media.json + a sample image
        run: |
          set -e
          mkdir -p images
          echo "fake image bytes" > images/sample-1.jpg
          cat > media.json << 'JSON'
          [
            {
              "id": "test-1",
              "caption": "Hello from GitHub Actions #analog",
              "media_url": "/images/sample-1.jpg",
              "permalink": "https://www.instagram.com/ravandeh.std/",
              "media_type": "IMAGE",
              "timestamp": "2025-01-01T00:00:00Z"
            }
          ]
          JSON
          echo "---- after write ----"
          ls -la
          git status

      - name: Commit & push to main (show full logs)
        run: |
          set -x
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git status
          git diff --staged --name-only || true
          git commit -m "TEST: write media.json (explicit push)" || echo "No changes to commit"
          # Push *explicitly* to main so we see an error if blocked
          git push origin HEAD:main
