name: Write media.json test (explicit push)
on:
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Create media.json + a sample image
        run: |
          mkdir -p images
          echo "placeholder" > images/sample-1.jpg
          cat > media.json << 'JSON'
          [
            {
              "id": "test-1",
              "caption": "Hello from GitHub Actions #analog",
              "media_url": "/images/sample-1.jpg",
              "permalink": "https://www.instagram.com/ravandeh.std/",
              "media_type": "IMAGE",
              "timestamp": "2025-01-01T00:00:00Z"
            }
          ]
          JSON

      - name: Commit & push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "TEST: write media.json (explicit push)" || echo "No changes"
          git push origin HEAD:main
